### ISSUE TITLE
Fatal Error: Install linuxbrew bash completion stuff

### ISSUE THREAD

**Issue by mictadlo** [galaxyproject/planemo-machine#88]
Hi,
I got the below error while executing `sudo make docker` under Mac OS X.

```
TASK [galaxyprojectdotorg.devbox : Install linuxbrew bash completion stuff] ****
fatal: [localhost]: FAILED! => {"changed": true, "cmd": "/home/ubuntu/.linuxbrew/bin/brew install -v bash-completion", "delta": "0:00:00.371178", "end": "2016-11-22 03:44:50.997213", "failed": true, "rc": 1, "start": "2016-11-22 03:44:50.626035", "stderr": "/home/ubuntu/.linuxbrew/Library/brew.sh: line 26: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8): No such file or directory\nError: undefined method `rebuild' for #<BottleSpecification:0x00000002dbac20>\nPlease report this bug:\n    https://github.com/Linuxbrew/linuxbrew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting\n/home/ubuntu/.linuxbrew/Library/Taps/homebrew/homebrew-core/Formula/bash-completion.rb:13:in `block in <class:BashCompletion>'\n/home/ubuntu/.linuxbrew/Library/Homebrew/software_spec.rb:91:in `instance_eval'\n/home/ubuntu/.linuxbrew/Library/Homebrew/software_spec.rb:91:in `bottle'\n/home/ubuntu/.linuxbrew/Library/Homebrew/formula.rb:1729:in `bottle'\n/home/ubuntu/.linuxbrew/Library/Taps/homebrew/homebrew-core/Formula/bash-completion.rb:11:in `<class:BashCompletion>'\n/home/ubuntu/.linuxbrew/Library/Taps/homebrew/homebrew-core/Formula/bash-completion.rb:3:in `load_formula'\n/home/ubuntu/.linuxbrew/Library/Homebrew/formulary.rb:21:in `module_eval'\n/home/ubuntu/.linuxbrew/Library/Homebrew/formulary.rb:21:in `load_formula'\n/home/ubuntu/.linuxbrew/Library/Homebrew/formulary.rb:34:in `load_formula_from_path'\n/home/ubuntu/.linuxbrew/Library/Homebrew/formulary.rb:83:in `load_file'\n/home/ubuntu/.linuxbrew/Library/Homebrew/formulary.rb:74:in `klass'\n/home/ubuntu/.linuxbrew/Library/Homebrew/formulary.rb:70:in `get_formula'\n/home/ubuntu/.linuxbrew/Library/Homebrew/formulary.rb:207:in `factory'\n/home/ubuntu/.linuxbrew/Library/Homebrew/formulary.rb:352:in `find_with_priority'\n/home/ubuntu/.linuxbrew/Library/Homebrew/extend/ARGV.rb:20:in `block in formulae'\n/home/ubuntu/.linuxbrew/Library/Homebrew/extend/ARGV.rb:16:in `map'\n/home/ubuntu/.linuxbrew/Library/Homebrew/extend/ARGV.rb:16:in `formulae'\n/home/ubuntu/.linuxbrew/Library/Homebrew/cmd/install.rb:44:in `install'\n/home/ubuntu/.linuxbrew/Library/brew.rb:84:in `<main>'", "stdout": "", "stdout_lines": [], "warnings": []}

	to retry, use: --limit @/tmp/ansible/provision.retry

PLAY RECAP *********************************************************************
localhost                  : ok=9    changed=8    unreachable=0    failed=1   

The command '/bin/sh -c ANSIBLE_FORCE_COLOR=1 PYTHONUNBUFFERED=1 ansible-playbook /tmp/ansible/provision.yml --tags=image        -c local -e "@vars.yml" $ANSIBLE_EXTRA_VARS &&     ANSIBLE_FORCE_COLOR=1 PYTHONUNBUFFERED=1 ansible-playbook /tmp/ansible/provision.yml --tags=database     -c local -e "@vars.yml" $ANSIBLE_EXTRA_VARS &&     ANSIBLE_FORCE_COLOR=1 PYTHONUNBUFFERED=1 ansible-playbook /tmp/ansible/provision.yml --tags=galaxy       -c local -e "@vars.yml" $ANSIBLE_EXTRA_VARS &&     ANSIBLE_FORCE_COLOR=1 PYTHONUNBUFFERED=1 ansible-playbook /tmp/ansible/provision.yml --tags=toolshed     -c local -e "@vars.yml" $ANSIBLE_EXTRA_VARS &&     ANSIBLE_FORCE_COLOR=1 PYTHONUNBUFFERED=1 ansible-playbook /tmp/ansible/provision.yml --tags=galaxyextras -c local -e "@vars.yml" $ANSIBLE_EXTRA_VARS &&     ANSIBLE_FORCE_COLOR=1 PYTHONUNBUFFERED=1 ansible-playbook /tmp/ansible/provision.yml --tags=devbox       -c local -e "@vars.yml" $ANSIBLE_EXTRA_VARS &&      sh /tmp/cleanup.sh &&     apt-get autoremove -y && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*' returned a non-zero code: 2
make: *** [docker] Error 2
```

What did I do wrong?

Thank you in advance.

Mic

**Comment by jmchilton** [comment]
I believe this https://github.com/galaxyproject/planemo-machine/commit/de1fdab104c97cca20a2d5c6eff8985186534ccc fixed that - sorry for the delay in responding to this. Thanks for the report and for trying to get this to work.
